### ISSUE TITLE
Incorrect commit link

### ISSUE THREAD

**Issue by johnnyBira** [uglow/conventional-changelog-angular-bitbucket#10]
The commit links in the generated change log looks like this:
`https://bitbucket.org/projects/humblebee/repos/customerportal-ui-components/commits/4cba59f`
But in my case the actual link should look like this with `projects` and `repos` omitted form the URL.
`https://bitbucket.org/humblebee/customerportal-ui-components/commits/4cba59f`

Are you following any certain conventions that I'm not aware of‚ or is there a way to alter the link through the options to match the path to the commit messages of my repo?

Thank you,
/John

**Comment by uglow** [comment]
Hi @johnnyBira , BitBucket repos have historically had a different URL scheme than GitHub for where commits and issues can be found. That's why I created this tool - to fix the URLs. 

But if what you are saying is accurate, then you may be able to use the regular `conventional-changelog-angular` preset, which is based on the GitHub URL scheme. Have you given that a try?

**Comment by uglow** [comment]
Related to PR #7.
